### ISSUE TITLE
Create Learn More Button

### ISSUE THREAD

**Issue by mailynnguyen** [acm-ucr/aviatr-website#5]
Create a learn more button that takes in a color parameter for the icon.
![Image](https://github.com/user-attachments/assets/f37e99ae-4153-40ca-979c-76f58ed874f0)
![Image](https://github.com/user-attachments/assets/01d23754-c35b-4a3a-82e4-3d60b0fb8f73)
![Image](https://github.com/user-attachments/assets/1b41ac41-d815-41ed-89fa-3d377c0c3608)

**Comment by raspberri05** [comment]
Hi, I am an open source contributor and would love to work on this issue

**Comment by raspberri05** [comment]
Created a PR for this issue 
Link to the PR: https://github.com/acm-ucr/aviatr-website/pull/18

**Comment by Kevinloritsch** [comment]
Sorry @raspberri05 we are not open for public development!
