### ISSUE TITLE
Make a Modal for Board Member Description

### ISSUE THREAD

**Issue by mailynnguyen** [acm-ucr/aviatr-website#86]
Design and make a modal that pops up when a board member image is clicked.

**Comment by Kevinloritsch** [comment]
![image](https://github.com/user-attachments/assets/e7106fe1-2b85-4be8-af03-bbc5a78f57a8)

A new addition to the FIGMA.

Props for hobbies, major, year, and description.
Colors should be static
Don't worry about mapping yet
If you could also get to the functionality of clicking on a board member to open and clicking close to exit (can be done with useState).
