### ISSUE TITLE
About Us Page Unify and Mobile Responsiveness

### ISSUE THREAD

**Issue by mailynnguyen** [acm-ucr/aviatr-website#87]
For some reason, the underline for the titles (Who We Are and What We Do) isn't showing up, please fix this.
Add the data to the board members.

https://docs.google.com/document/d/1PkgW6dOMwlg41S6FTy0jpJiBCiIKtOP9IiiheFcKlU0/edit?tab=t.0

Make the entire page mobile responsive.

**Comment by Kevinloritsch** [comment]
Will be only 6 board members instead of the original 8
